name: Build Pro Dylib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          rm -rf ~/theos
          git clone --recursive https://github.com/theos/theos.git ~/theos
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/archive/master.tar.gz | tar -xz -C ~/theos/sdks --strip-components=1
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Install Signing Tools
        run: |
          brew install ldid

      - name: Build Dylib
        run: |
          export THEOS=~/theos
          make FINALPACKAGE=1
          # أمر سحري: انسخ أي ملف dylib للمجلد الرئيسي عشان السيرفر يشوفه
          find .theos/obj -name "*.dylib" -exec cp {} . \;

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mohammed_Dylib_Final
          # توة المسار صار في المجلد الرئيسي مباشرة
          path: "./*.dylib"
